language: generic 
sudo: required 
services: 
  - docker

before_install:
  - docker build -t kevinisback/client-test -f ./client/Dockerfile.dev ./client

test:
  - docker run -e CI=true kevinisback/client-test npm test

after_success:
  - docker build -t kevinisback/multi-client ./client
  - docker build -t kevinisback/multi-worker ./worker
  - docker build -t kevinisback/multi-server ./server
  - docker build -t kevinisback/multi-nginx ./nginx
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push kevinisback/multi-client
  - docker push kevinisback/multi-worker
  - docker push kevinisback/multi-nginx
  - docker push kevinisback/multi-server

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-118408643293'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
